[package]
name = "rticx-cortex-m-macro"
version = "0.2.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Proc-macro crate for the RTICX Cortex-M distribution"
keywords = ["rtic", "rticx", "cortex-m", "proc-macro", "embedded"]
categories = ["no-std", "embedded"]
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
rticx-core = { workspace = true }
syn = { workspace = true }
rticx-sw-pass = { workspace = true }
rticx-async-pass = { workspace = true }

[features]
swtasks = []
armv6m = []
async = []
