[package]
name = "rticx-async"
version = "0.1.0"
edition = "2024"
authors = ["Zakaria Madaoui"]
description = "Async runtime primitives for RTICX: channels, executor slots, and waker infrastructure"
license = "MIT"
repository = "https://github.com/rticx-rs/rticx"
keywords = ["rtic", "rticx", "async", "embedded", "concurrency"]
categories = ["no-std", "embedded", "asynchronous"]

[dependencies]
heapless = "0.9"
critical-section = "1"
portable-atomic = { version = "1.15.0", default-features = false }

[dev-dependencies]
critical-section = { version = "1", features = ["std"] }

[features]
default = []
# if the target doesn't support atomics
atomic-critical-section = ["portable-atomic/critical-section"]
