[package]
name = "rticx-async"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Async runtime primitives for RTICX: channels, executor slots, and waker infrastructure"
keywords = ["rtic", "rticx", "async", "embedded", "concurrency"]
categories = ["no-std", "embedded", "asynchronous"]

[dependencies]
heapless = "0.9"
critical-section = "1"
portable-atomic = { version = "1.15.0", default-features = false }

[dev-dependencies]
critical-section = { version = "1", features = ["std"] }

[features]
default = []
# if the target doesn't support atomics
atomic-critical-section = ["portable-atomic/critical-section"]
