[package]
name = "rticx-cortex-m"
version = "0.2.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "RTICX distribution for single-core Cortex-M targets (armv6-m and armv7-m and above)"
keywords = ["rtic", "rticx", "cortex-m", "arm", "embedded"]
categories = ["no-std", "embedded"]
readme = "README.md"

[lib]
test = false
bench = false

[dependencies]
cortex-m = "0.7.8"
rticx-cortex-m-macro = { workspace = true }
rticx-async = { workspace = true, optional = true }
rticx-spsc = { workspace = true }

[features]
# Use interrupt source-masking for locking (armv6-m: Cortex-M0/M0+/M23).
# When disabled (default), BASEPRI-based locking is used (armv7-m and above).
armv6m = ["rticx-cortex-m-macro/armv6m", "rticx-async/atomic-critical-section"]
# Software tasks pass. Mutually exclusive with `async`
swtasks = ["rticx-cortex-m-macro/swtasks"]
# Async/await software tasks support (rticx-async-pass). Mutually exclusive with `swtasks`.
async = [
    "rticx-cortex-m-macro/async",
    "dep:rticx-async",
    "cortex-m/critical-section-single-core",
]
