[package]
name = "rticx-xbin-driver"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "`cargo-xbin` driver for the RTICX multi-binary extension"
keywords = ["rtic", "rticx", "ipc", "cargo-subcommand", "multicore"]
categories = ["command-line-utilities", "development-tools::cargo-plugins"]
publish = false

[[bin]]
name = "cargo-xbin"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
rticx-xbin-proto = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3.27.0"
