[package]
name = "rticx-async-pass"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Async tasks compilation pass for the RTICX real-time concurrency framework"
keywords = ["rtic", "rticx", "async", "embedded", "concurrency"]
categories = ["no-std", "embedded"]
readme = "README.md"

[dependencies]
heck = { version = "0.5.0" }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
rticx-core = { workspace = true }
rticx-sw-pass = { version = "0.2.0", path = "../rticx-sw-pass" }

[dev-dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits", "full"] }
