[package]
name = "rticx-auto-assign"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Automatic core assignment compilation pass for the RTICX multicore framework"
keywords = ["rtic", "rticx", "multicore", "embedded", "concurrency"]
categories = ["no-std", "embedded"]
readme = "README.md"

[dependencies]
heck = { version = "0.5.0" }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
rticx-core = { workspace = true }
thiserror = { workspace = true }
