use super::*;

/// Interface for providing the low-level hardware bindings specific for a target(s) (A.k.a The Backend) to be used during code generation phase
/// of the **Core Compilation Pass**.
pub trait CorePassBackend {
    /// Code emitted **after** `#[init]` and all task `init()` functions,
    /// but **before** the idle loop begins.  Runs inside a critical
    /// section (interrupts disabled).
    ///
    /// This is the place to:
    /// * Set interrupt priorities via the NVIC (or equivalent controller).
    /// * Unmask interrupt lines used by hardware tasks and dispatchers.
    /// * On multicore targets: wake up and initialize secondary cores.
    ///
    /// # Contract
    ///
    /// Return `None` to emit nothing, or `Some(token_stream)` containing
    /// the target-specific initialization code.
    ///
    /// # Porting
    ///
    /// Iterate over `app_analysis.used_irqs` to configure every interrupt
    /// the application depends on.  For each IRQ you typically:
    /// 1. Set its priority (clamped to `MIN_TASK_PRIORITY`).
    /// 2. Unmask it (NVIC::unmask or equivalent).
    ///
    /// Access the PAC path via `app_args.pacs[app_info.core as usize]`.
    ///
    /// On single-core targets the `core` field of `app_info` is always `0`.
    ///
    /// Reference: `rticx-cortex-m` configures exceptions via SCB and external
    /// interrupts via NVIC. `rticx-rp2040` adds core-1 boot and FIFO setup.
    fn post_init(
        &self,
        app_args: &AppArgs,
        app_info: &SubApp,
        app_analysis: &SubAnalysis,
    ) -> Option<TokenStream2>;

    /// # SRP-based Resource Locking
    ///
    /// The core pass generates an incomplete `lock` function for each
    /// shared-resource proxy.  This method must append the hardware-
    /// specific locking body to it.
    ///
    /// To illustrate, assume the user defined:
    ///
    /// ```rust
    /// // Before code expansion
    /// #[shared]
    /// struct Shared {
    ///     pub resource1: R1Type
    /// }
    /// ```
    ///
    /// Every field has a corresponding autogenerated **resource proxy**
    /// struct implementing the `RticMutex` internal trait:
    ///
    /// ```rust
    /// struct __resource1_mutex<const TASK_PRIORITY: u16>;
    /// impl<const TASK_PRIORITY: u16> RticMutex for __resource1_mutex<TASK_PRIORITY> {
    ///     type ResourceType = R1Type;
    ///     // this is what `incomplete_lock_fn` already contains
    ///     fn lock<R>(&mut self, f: impl FnOnce(&mut Self::ResourceType) -> R) -> R {
    ///         const CEILING: u16 = 3u16; // resource ceiling
    ///         let task_priority = TASK_PRIORITY;
    ///         let resource_ptr = unsafe { &mut SHARED.assume_init_mut().resource1 };
    ///         /* TODO: HARDWARE-SPECIFIC CODE COMES HERE */
    ///     }
    /// }
    /// ```
    ///
    /// You can inspect the incomplete function by adding a debug print
    /// in your implementation:
    ///
    /// ```ignore
    /// eprintln!("{}", incomplete_lock_fn.to_token_stream());
    /// ```
    ///
    /// The function's source can also be found in
    /// `rticx-core/src/common_internal/rticx_functions.rs`
    /// (`fn get_resource_proxy_lock_fn`).
    ///
    /// ## Contract
    ///
    /// * The returned function must have the same signature as
    ///   `incomplete_lock_fn`.
    /// * The implementation must follow SRP rules:
    ///   1. Raise the system interrupt priority ceiling to `CEILING`.
    ///   2. Call the closure `f`, passing `resource_ptr` as the argument
    ///      (this executes the resource critical section).
    ///   3. Restore the system interrupt priority ceiling to
    ///      `task_priority`.
    /// * If the locking body needs global definitions (constants, `use`
    ///   items, helper functions), emit them via
    ///   [`generate_global_definitions`](CorePassBackend::generate_global_definitions).
    ///
    /// ## Note
    /// This method is called once per shared resource per sub-application.
    ///
    /// ## Reference
    ///
    /// * **Cortex-M (BASEPRI)**: delegates to
    ///   `<distro>::export::lock(resource_ptr, CEILING as u8,
    ///   PAC::NVIC_PRIO_BITS, f)`.
    /// * **Cortex-M (armv6m source-mask)**: same call, but the `Mask`
    ///   type and `NVIC_PRIO_BITS` come from the source-masking
    ///   export.
    /// * **RISC-V mintthresh**: raise `mintthresh`, call `f`, restore.
    /// * **RISC-V CLIC**: raise the CLIC level, call `f`, restore.
    fn generate_resource_proxy_lock_impl(
        &self,
        app_args: &AppArgs,
        app_info: &SubApp,
        incomplete_lock_fn: syn::ImplItemFn,
    ) -> syn::ImplItemFn;

    /// Global definitions emitted into the app module root.
    ///
    /// Return a `TokenStream` of items (constants, `use` statements,
    /// helper functions) that the other bindings may refer to.
    ///
    /// Reference: `rticx-cortex-m` (armv6m), `rticx-riscv (slic)`
    fn generate_global_definitions(
        &self,
        app_args: &AppArgs,
        app_info: &SubApp,
        app_analysis: &SubAnalysis,
    ) -> Option<TokenStream2>;

    /// Wrapping code emitted around every task's `exec()` call.
    ///
    /// The generated interrupt handler calls `exec()` inside whatever
    /// token stream you return here.  This is used to save/restore
    /// state around task execution.
    ///
    /// # Porting
    ///
    /// * **BASEPRI** -- save BASEPRI before, restore after.
    /// * **Source-mask** -- no-op (lock primitive handles it).
    /// * **Threshold** -- save threshold before, restore after.
    ///
    /// Return `None` to skip wrapping entirely.
    ///
    /// Reference: `rticx-cortex-m` implements execution wrapping for non-armv6m targets
    fn wrap_task_execution(
        &self,
        task: &RticTask,
        dispatch_task_call: TokenStream2,
    ) -> Option<TokenStream2>;

    /// Name of the entry function for each core.
    ///
    /// # Contract
    /// * **Single-core**: always return `"main"`.
    /// * **Multicore**: return `"main"` for core 0, and a unique identifier (e.g. `core1_entry`) for others.
    ///
    /// References:
    /// - `rticx-cortex-m` always returns `"main"`.
    /// - `rticx-rp2040` returns `"main"` for core 0 and `"core{N}_entry"` for core N > 0.
    fn entry_name(&self, core: u32) -> Ident;

    /// Custom body for the default idle loop.
    ///
    /// When the user does not define an `#[idle]` task, RTIC generates
    /// one with an infinite loop.  This method populates that loop.
    ///
    /// You can return `Some(quote! { wfi(); })` to have the CPU sleep between
    /// interrupts (saves power).  Return `None` for an empty busy loop.
    ///
    /// Reference: `rticx-cortex-m` emits `rticx_cortex_m::export::wfi()`.
    fn populate_idle_loop(&self) -> Option<TokenStream2>;

    /// Statement that enables **global system interrupts**, emitted after
    /// the initialization critical section (after `post_init`) and before
    /// the idle loop / user `post_init` function.
    ///
    /// # Why is this needed?
    ///
    /// The initialization critical section restores the global interrupt
    /// state it found on entry. On targets where global interrupts are
    /// **disabled by default** at boot (e.g. RISC-V: `mstatus.MIE` starts
    /// cleared), interrupts remain disabled after initialization unless the
    /// backend explicitly enables them here.
    ///
    /// On targets where global interrupts are **enabled by default** (e.g.
    /// Cortex-M: PRIMASK cleared at reset), return `None`.
    ///
    /// # Contract
    ///
    /// Return `None` to emit nothing, or `Some(token_stream)` containing a
    /// statement (or block) that enables global interrupts. The statement
    /// is emitted after all interrupt initialization (`post_init`) has run,
    /// so it may assume the interrupt controller is fully configured.
    ///
    /// # Reference
    ///
    /// * **Cortex-M**: `None` (interrupts enabled by default).
    /// * **RISC-V**: `unsafe { <distro>::export::interrupt::enable(); }`.
    fn generate_enable_global_interrupts(&self) -> Option<TokenStream2>;

    /// Body of the global critical-section function.
    ///
    /// RTIC generates a function like:
    ///
    /// ```ignore
    /// pub fn __rticx_critical_section<F, R>(f: F) -> R
    /// where F: FnOnce() -> R { /* YOU FILL THIS */ }
    /// ```
    ///
    /// # Contract
    /// * Do NOT change the function signature of `empty_body_fn`.
    /// * The function must re-enable interrupts when done.
    ///
    /// The function must implement a critical section by:
    /// 1- storing the state of global interrupts
    /// 2- disable global interrupts
    /// 3- execute the closure and get the return value
    /// 4- restore the state of global interrupts
    /// 5- return the produced by the closure
    ///
    /// The reason for saving and restoring global interrupt state is due to the fact that
    /// Critical section function can be nested
    ///
    /// # Porting
    ///
    /// * **Cortex-M**: `cortex_m::interrupt::free`.
    /// * **RISC-V**: disable/enable/restore global interrupt via `mstatus.MIE`.
    fn generate_interrupt_free_fn(&self, empty_body_fn: syn::ItemFn) -> syn::ItemFn;

    /// Validation hook called after parsing and analysis, but before
    /// code generation.
    ///
    /// Use this to reject user code that is invalid for your target.
    ///
    /// # Porting
    ///
    /// * **Cortex-M**: reject tasks bound to non-configurable exceptions
    ///   (`NonMaskableInt`, `HardFault`).
    /// * **Single-core**: reject `core = N` where N > 0.
    /// * **RISC-V**: reject interrupts that cannot be used as dispatchers.
    ///
    /// Return `Ok(())` to allow codegen, or `Err(syn::Error)` to abort.
    ///
    /// Reference: `rticx-cortex-m` checks against `NON_CONFIGURABLE_EXCEPTIONS`.
    fn pre_codegen_validation(&self, app: &App, analysis: &Analysis) -> syn::Result<()>;

    /// Attribute macros to add to the entry point.
    ///
    /// Used to annotate the runtime entry point for bare metal applications.
    ///
    /// # Examples
    ///
    /// ```rust
    /// #[riscv_rt::entry]
    /// fn main() -> ! {
    ///     loop {}
    /// }
    /// ```
    fn entry_attrs(&self) -> Vec<syn::Attribute> {
        vec![]
    }

    /// Attribute macros to add to a task's interrupt handlers.
    ///
    /// Used by some implementations to inject custom attributes onto
    /// task handler functions.
    ///
    /// # Examples
    ///
    /// ```rust
    /// #[export_name = "interrupt17"]
    /// fn GPIO() {}
    /// ```
    fn task_attrs(&self, _interrupt_name: syn::Ident) -> Vec<syn::Attribute> {
        vec![]
    }

    /// Subscribe to info_bus
    /// This method is guaranteed to be called before any other methods in this trait.
    fn subscribe(&mut self, _info_bus: InfoBus) {}
}
