[package]
name = "rticx-sw-pass"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Software tasks compilation pass for the RTICX framework: dispatchers, message queues, spawn, spawn_from"
keywords = ["rtic", "rticx", "software-tasks", "embedded", "concurrency"]
categories = ["no-std", "embedded"]
readme = "README.md"

[dependencies]
heck = { version = "0.5.0" }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
rticx-core = { workspace = true }
rticx-spsc = { workspace = true }

[dev-dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits", "full"] }
